#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Satark knowledge base generator.
# Source: Astra/Sol Prompt #1 output (49 signals). reason/citation/action/
# weight/category are integrated VERBATIM. Two engineering passes applied:
#   (1) JSON-validity fix: Astra emitted single-backslash regex escapes that are
#       invalid JSON (\s, \b -> parse error / wrong char). Regexes are authored
#       here as Python raw strings so json.dump serialises them correctly for
#       `new RegExp(src,'i')`.
#   (2) Precision-safe detector hardening on high-value signals so real-world
#       phrasings ("guaranteed 300% returns", "join our Telegram", "pay to
#       activate", "AnyDesk") are caught; one classic signal restored
#       (claims_sebi_registration); one false-positive-prone detector removed
#       (bare UPI-handle regex). Deeper tuning is benchmark-driven (Prompt #4).
# Output: src/data/knowledge-base.json  (version "1.0", schema frozen).
import json, pathlib

def s(sid, cat, sev, w, label, kw, reason, cite, action, rx=None):
    return {
        "id": sid, "category": cat, "severity": sev, "weight": w,
        "label": {"en": label},
        "detect": {"keywords": kw, "regex": list(rx or [])},
        "reason": {"en": reason},
        "citation": {"label": cite, "url": None},
        "action": {"en": action},
    }

SIGNALS = [
 s("guaranteed_returns","fraud","critical",90,"Guaranteed returns",
   ["guaranteed returns","assured returns","assured return","guaranteed return","guaranteed profit","guaranteed income","fixed monthly profit","double your money","sure shot","sure-shot"],
   "No genuine market investment can promise returns without risk. Such promises are commonly used to make a person send money quickly.",
   "SEBI investor warnings on guaranteed returns",
   "Do not send money; verify the person and service through the official SEBI website.",
   [r"guaranteed\s+\d{1,4}\s*%", r"\d{1,4}\s*%\s*(?:guaranteed|assured|monthly|weekly|daily|returns?|profit)", r"guaranteed\s+(?:returns?|profit|income|money)"]),
 s("assured_profit_promise","fraud","critical",88,"Assured profit promise",
   ["assured profit","profit is guaranteed","no loss strategy"],
   "A claim of profit with no chance of loss is not normal market language. It can hide a fraudulent scheme or an unregistered service.",
   "SEBI (Prohibition of Fraudulent and Unfair Trade Practices) Regulations, 2003",
   "Treat the claim as unsafe and do not act until an independent official check is complete."),
 s("sebi_approved_claim","impersonation","critical",86,"Fake SEBI approval claim",
   ["sebi approved scheme","approved by sebi","sebi guaranteed"],
   "SEBI registration does not mean that SEBI guarantees returns or approves a private profit promise. Fraudsters misuse SEBI's name to create trust.",
   "SEBI investor guidance on registration and approval claims",
   "Check the exact entity name and registration details on SEBI's official intermediary search."),
 s("claims_sebi_registration","impersonation","medium",48,"Claims to be SEBI registered",
   ["sebi registered","sebi-registered","registered with sebi","sebi certified","sebi regd"],
   "Anyone can type 'SEBI registered' in a message. The claim is not proof; scammers copy or invent registration details to look trustworthy. A real registration must be checked by exact name and number.",
   "SEBI intermediary registration — verify on SEBI's official register",
   "Verify the exact name and registration number on SEBI's official website before trusting the claim."),
 s("fake_sebi_registration_number","impersonation","critical",88,"Suspicious SEBI number",
   ["sebi registration no","sebi reg number","registration certificate attached"],
   "A number shown in a message may be copied, altered, or linked to another entity. A number alone does not prove that the sender is genuine.",
   "SEBI intermediary registration and verification mechanism",
   "Search the number and legal name independently on the official SEBI website, without using the message link.",
   [r"\bsebi\s*(?:reg(?:istration)?|licen[cs]e)\s*(?:no|number|id)?\s*[:#-]?\s*[a-z0-9/-]{5,}\b"]),
 s("fake_exchange_registration","impersonation","critical",84,"Fake exchange registration",
   ["nse approved account","bse registered agent","exchange certified trader"],
   "Fraudsters may use exchange names or logos to appear legitimate. Exchange membership must be checked through the exchange's official directory.",
   "NSE and BSE authorised member verification mechanisms",
   "Verify the member or intermediary directly on the official exchange website."),
 s("impersonated_registered_adviser","impersonation","critical",86,"Impersonated adviser",
   ["official sebi advisor","speaking on behalf of your adviser","same name as registered adviser"],
   "Scammers copy the name, logo, photographs, or registration details of a real adviser. The real firm may have no connection with the message.",
   "SEBI (Investment Advisers) Regulations, 2013",
   "Call the adviser using contact details from its official website or SEBI record."),
 s("cloned_broker_app","technical","critical",90,"Cloned broker application",
   ["new trading app download","exclusive broker app","copy trading application"],
   "A fake application can show false balances and capture passwords or money. A familiar logo does not prove that the application is genuine.",
   "SEBI investor alerts on fake trading applications",
   "Use only the application store link published on your broker's verified official website.",
   [r"\b(?:download|install)\s+(?:our|the)\s+(?:new|exclusive)\s+(?:trading|broker|investment)\s+app\b"]),
 s("cloned_broker_website","technical","high",70,"Lookalike broker website",
   ["secure broker login link","new trading portal","official account activation website"],
   "A copied website may collect login details while looking like a real broker. Small changes in the domain name can be hard to notice on a phone.",
   "SEBI and CERT-In phishing safety guidance",
   "Close the link and type the broker's known website address yourself."),
 s("sideloaded_apk_request","technical","critical",88,"Sideloaded APK request",
   ["install apk","download apk file","allow unknown sources"],
   "An APK sent through chat can contain malware and may bypass store safety checks. It can steal banking details or control the phone.",
   "RBI advisory on mobile and digital payment security",
   "Do not install the file; delete it and scan the phone with trusted security tools."),
 s("fake_ipo_allotment","fraud","critical",86,"Fake IPO allotment",
   ["confirmed ipo allotment","ipo allotment fee","guaranteed ipo shares"],
   "IPO allotments follow formal application and registrar processes. A message demanding money for a guaranteed allotment is a strong fraud warning.",
   "SEBI public issue and IPO application framework",
   "Check the application and allotment only through the recognised exchange, registrar, or bank channel."),
 s("fake_sme_allotment","fraud","critical",84,"Fake SME allotment",
   ["sme ipo confirmed","pre allotment of sme shares","sme allotment payment"],
   "A private message cannot reserve or guarantee SME IPO shares. Fraudsters often use unfamiliar company names to demand advance payments.",
   "SEBI public issue framework for SME platforms",
   "Verify the issue on the official exchange and never pay a personal account for allotment."),
 s("grey_market_pre_ipo_promise","fraud","high",72,"Guaranteed pre-IPO deal",
   ["pre ipo guaranteed","grey market allotment","pre ipo fixed profit"],
   "Grey-market dealings may lack normal investor protections and can involve false allotment claims. A guaranteed pre-IPO gain is especially unsafe.",
   "SEBI investor cautions on unregulated securities offers",
   "Do not transfer money for an informal pre-IPO offer; use only regulated public issue channels."),
 s("pump_dump_small_cap_tip","fraud","high",72,"Small-cap pump signal",
   ["small cap will explode","operator backed share","multibagger penny stock tip"],
   "Promoters may spread excitement to push up a thinly traded share and then sell. A sudden tip about a little-known company needs strong caution.",
   "SEBI (Prohibition of Fraudulent and Unfair Trade Practices) Regulations, 2003",
   "Do not trade from the message; save the evidence and verify the information from official disclosures."),
 s("telegram_vip_tips","fraud","high",68,"VIP tips channel",
   ["telegram vip tips","whatsapp premium calls","exclusive intraday signals group","vip telegram","join our telegram","join telegram","telegram channel","tips group","signals group"],
   "Private tip groups can hide the identity and history of the person making the claims. Paid access does not prove registration or accuracy.",
   "SEBI (Research Analysts) Regulations, 2014",
   "Do not pay for access until the provider's registration and identity are independently verified.",
   [r"(?:t\.me|telegram\.me|chat\.whatsapp\.com)/[^\s]+"]),
 s("upfront_activation_fee","fraud","high",70,"Upfront activation fee",
   ["pay activation fee","account opening charge now","release your profit fee","pay to activate","to activate your account","activation charge"],
   "Fraudsters use small urgent fees to test whether a person will keep paying. More fees often follow after the first transfer.",
   "RBI digital payment fraud awareness guidance",
   "Stop the payment and contact the bank through its official customer-care channel."),
 s("vip_membership_fee","fraud","high",64,"VIP membership fee",
   ["vip investment membership","premium signal subscription payment","join elite profit group"],
   "A membership label can make a risky offer look exclusive and trustworthy. It does not establish that the provider is regulated.",
   "SEBI investor education on unregistered investment advice",
   "Verify the provider's registration before sharing money or personal details."),
 s("fake_profit_screenshots","misinformation","high",62,"Fake profit screenshots",
   ["profit screenshot proof","withdrawal screenshot","client earnings screenshot"],
   "Screenshots can be edited or taken from another account. They do not prove that the platform is genuine or that money can be withdrawn.",
   "SEBI investor caution on testimonials and performance claims",
   "Treat screenshots as unverified evidence and do not transfer money because of them."),
 s("fake_testimonials","misinformation","medium",50,"Unverified testimonials",
   ["real client success story","ordinary people became rich","verified customer profit"],
   "Testimonials may be paid, copied, or completely false. A story about someone else's result cannot establish safety.",
   "SEBI advertising and investor-protection principles",
   "Ask for independently verifiable records instead of relying on testimonials."),
 s("personal_upi_payment","fraud","critical",86,"Personal UPI payment",
   ["send to my upi","pay personal upi id","transfer to individual account","pay to my upi"],
   "A personal UPI ID may send money to an individual instead of a regulated business. Recovery can be difficult after the transfer.",
   "RBI digital payment safety guidance",
   "Do not pay; verify the beneficiary name in the payment screen and use only official payment routes."),
 s("personal_bank_account_payment","fraud","critical",86,"Personal bank transfer",
   ["transfer to my savings account","pay into personal bank account","beneficiary is an individual"],
   "Investment money should not normally be sent to an unrelated person's savings account. This is a common way to move scam proceeds.",
   "RBI customer-protection and digital payment fraud guidance",
   "Stop the transfer and confirm the beneficiary with the regulated institution using an official number."),
 s("fake_refund_request","fraud","critical",88,"Fake refund demand",
   ["sebi refund processing fee","exchange refund tax","broker refund release charge"],
   "A person claiming to release a refund may demand another payment first. Official complaint or refund processes do not make an unknown caller trustworthy.",
   "SCORES — SEBI complaint redress",
   "Do not pay the caller; contact the original institution through its official website."),
 s("recovery_scam","fraud","critical",90,"Recovery scam",
   ["recover your lost investment","pay recovery charges","lawyer can recover funds"],
   "After a loss, scammers may promise recovery and request fees or account access. This can create a second loss.",
   "National Cyber Crime helpline 1930 and cybercrime.gov.in",
   "Do not pay a recovery agent; report the original fraud promptly through 1930 or cybercrime.gov.in."),
 s("fake_customer_care","impersonation","critical",84,"Fake customer care",
   ["customer care whatsapp number","official support number in message","call this refund helpline"],
   "Search results and social messages can display fake support numbers. A caller may ask for OTPs, remote access, or a transfer.",
   "RBI customer-care and digital payment safety guidance",
   "Find customer care only inside the official app, bank statement, or verified website."),
 s("digital_arrest_impersonation","impersonation","critical",92,"Digital arrest threat",
   ["digital arrest","video call police verification","sebi cyber crime case"],
   "Police, SEBI, or courts do not conduct a digital arrest through a threatening video call. Scammers use fear to force immediate payments.",
   "Indian cybercrime advisories on digital arrest scams",
   "End the call, do not transfer money, and report the incident to 1930 or the nearest police station."),
 s("dabba_trading_offer","fraud","critical",88,"Dabba trading offer",
   ["dabba trading","off market trading account","trade without demat"],
   "Dabba trading records bets outside recognised exchanges and removes normal investor protections. The operator can refuse withdrawals or disappear.",
   "SEBI warnings on illegal dabba trading",
   "Do not open the account; use only a verified broker connected to a recognised exchange."),
 s("unregistered_trading_platform","fraud","critical",84,"Unregistered trading platform",
   ["private trading platform","unregistered broker app","trade directly with operator"],
   "A platform outside the regulated system may show invented prices or balances. It may provide no reliable complaint or recovery route.",
   "SEBI intermediary registration framework",
   "Check the broker in the official exchange and SEBI directories before registering."),
 s("forex_money_doubling","fraud","critical",86,"Forex doubling scheme",
   ["forex money doubling","double your currency","fixed forex income"],
   "Money-doubling claims hide high risk and may involve unauthorised platforms or payment routes. A foreign-exchange label does not make a scheme legal.",
   "RBI foreign exchange and unauthorised electronic trading platform advisories",
   "Do not deposit funds; check whether the entity is authorised by the relevant Indian regulator."),
 s("crypto_money_doubling","fraud","high",78,"Crypto doubling scheme",
   ["crypto double deposit","send bitcoin get double","guaranteed crypto yield"],
   "Doubling schemes commonly use fake wallets or social accounts and cannot guarantee repayment. Crypto transfers are often difficult to reverse.",
   "Indian cybercrime advisories on cryptocurrency investment scams",
   "Do not send crypto or money; preserve the wallet address and report suspected fraud."),
 s("task_investment_job_scam","fraud","high",78,"Task investment job scam",
   ["part time investment job","complete tasks to earn profit","recharge wallet for commission"],
   "A fake job may show small early rewards and then demand larger deposits to unlock tasks. Employment should not require investment payments.",
   "National Cyber Crime advisories on task-based fraud",
   "Do not deposit money for a job; block the contact and report any payment fraud quickly."),
 s("deepfake_finfluencer","impersonation","high",72,"Impersonated finfluencer",
   ["celebrity investment video","ai generated finance video","finfluencer recommends private link"],
   "A face or voice in a video can be copied or generated. Public figures may have no connection with the account or offer.",
   "SEBI investor warnings on impersonation and social-media fraud",
   "Verify the post on the person's official verified account and do not use a private payment link."),
 s("loan_to_invest_pressure","behavioral","high",66,"Pressure to borrow",
   ["take a loan to invest","borrow and multiply","use credit card for investment"],
   "Borrowing increases pressure because the loan must be repaid even if the investment loses value. Fraudsters use this pressure to increase the amount sent.",
   "SEBI investor education on risk and leverage",
   "Pause and do not borrow or pledge assets because of a message or caller."),
 s("remote_access_app_request","technical","critical",90,"Remote access request",
   ["install anydesk","teamviewer support","give remote access","anydesk","teamviewer","quicksupport","rustdesk"],
   "Remote-access tools can let another person see or control the phone. They may observe OTPs, banking screens, or payment authorisations.",
   "RBI advisory on remote-access and screen-sharing applications",
   "Never install remote-access software for an unknown caller; uninstall it and contact your bank if it was used."),
 s("otp_pin_password_request","technical","critical",92,"Credential request",
   ["share otp","share your otp","send otp","send your otp","tell me your otp","what is your otp","tell me your upi pin","send your trading password","share your password","share your cvv"],
   "Banks, brokers, exchanges, and regulators do not need your OTP, PIN, password, or CVV to give support. Sharing them can allow unauthorised access.",
   "RBI never-share OTP, PIN, password, and CVV guidance",
   "Do not share the credential; change it immediately if it was already disclosed."),
 s("screen_share_request","technical","critical",84,"Screen-sharing request",
   ["share your screen","share screen","start screen recording","show banking screen on video"],
   "A shared screen can reveal account numbers, OTPs, PIN entry, or private messages. A support person does not need to watch your entire screen.",
   "RBI digital banking safety guidance",
   "Refuse the request and close the call or chat."),
 s("link_shortener","technical","high",60,"Hidden destination link",
   ["bit.ly investment link","tinyurl account verification","short link to trading app"],
   "A shortened link hides the real website and can lead to phishing or malware. It is difficult to check the destination before opening it.",
   "CERT-In phishing and malicious-link safety guidance",
   "Do not open the short link; find the organisation's website independently.",
   [r"\b(?:https?://)?(?:bit\.ly|tinyurl\.com|t\.co|cutt\.ly|rb\.gy)/[a-z0-9-]+\b"]),
 s("lookalike_punycode_domain","technical","high",68,"Lookalike domain",
   ["xn--","sebi-support dot com","broker-login security"],
   "A lookalike or punycode domain can resemble a trusted name while being controlled by someone else. The spelling may be hard to notice on a small screen.",
   "CERT-In domain and phishing safety guidance",
   "Do not log in; use a saved official bookmark or manually typed domain.",
   [r"https?://[^\s]*xn--[^\s]*"]),
 s("kyc_blocked_phishing","technical","high",74,"KYC blocking threat",
   ["kyc expires today","account blocked unless kyc","pan verification urgent link"],
   "Scammers create fear that an account will be blocked and then collect identity or banking details. Genuine KYC updates should use the institution's known channel.",
   "RBI KYC fraud advisories and customer-protection guidance",
   "Ignore the message link and check KYC status inside the official bank or broker application."),
 s("affiliate_promotional_content","misinformation","medium",42,"Promotional content marker",
   ["affiliate link","use my referral code","link in bio for account"],
   "The speaker may earn money when you click, join, or deposit. Promotional content is not independent investor education.",
   "SEBI guidance on advertising and disclosure by investment-related persons",
   "Check whether the speaker clearly discloses the commercial relationship before taking any action."),
 s("dm_private_offer","behavioral","medium",48,"Private offer invitation",
   ["dm me for entry","message me privately","exclusive offer inbox"],
   "Moving a financial offer to private chat reduces visibility and makes checking the claims harder. It can also enable pressure and repeated requests for money.",
   "SEBI social-media investor-protection guidance",
   "Keep communication in a verifiable official channel and do not share personal documents in private chat."),
 s("absolute_success_claim","misinformation","high",70,"Absolute success claim",
   ["will definitely rise","sure shot profit","guaranteed multibagger"],
   "Absolute words hide uncertainty and can be used to sell a tip. Markets cannot be described honestly as certain.",
   "SEBI (Research Analysts) Regulations, 2014",
   "Treat the claim as promotional and seek independently verified information."),
 s("no_risk_disclosure","misinformation","medium",44,"Missing risk disclosure",
   ["profits only no risk","risk free opportunity","losses are impossible"],
   "A serious financial communication should explain that value can fall and losses are possible. Omitting risk can create a misleading impression.",
   "SEBI advertising code and investor-risk disclosure principles",
   "Pause and look for clear risk information from an authorised source."),
 s("registration_used_as_sales_proof","misinformation","high",62,"Registration used to sell",
   ["sebi registered so profit","registered means no loss","sebi number proves returns"],
   "Registration identifies a regulated role; it does not guarantee performance or protect every transaction. Fraudsters use the word as a sales shortcut.",
   "SEBI intermediary registration and investor-protection guidance",
   "Verify both the registration and the exact service being offered."),
 s("herd_fomo_framing","behavioral","medium",46,"Herd and FOMO pressure",
   ["everyone is joining","all members are earning","do not miss this opportunity"],
   "Popularity does not prove safety or legality. Fraudsters use group success stories to reduce careful checking.",
   "SEBI investor education on behavioural risks",
   "Make no payment until you have checked the entity and offer independently."),
 s("artificial_urgency","behavioral","high",64,"Artificial urgency",
   ["pay within one hour","offer expires tonight","last chance to join","act now","offer ends today"],
   "Urgency prevents a person from checking registration, beneficiary details, and complaints. A genuine service should allow time for verification.",
   "SEBI investor-protection guidance on pressure tactics",
   "Stop and wait; verify the offer through an independent official source."),
 s("artificial_scarcity","behavioral","medium",44,"Artificial scarcity",
   ["only five slots left","limited investor seats","exclusive allotment closes now","few seats left","slots left"],
   "Scarcity claims can make a person act before checking facts. They are especially suspicious when linked to a private payment.",
   "SEBI investor education on misleading solicitations",
   "Ignore the deadline and verify whether the opportunity exists through official records."),
 s("secrecy_instruction","behavioral","high",66,"Secrecy instruction",
   ["do not tell anyone","keep this confidential","hide this from your family"],
   "A demand for secrecy stops family members or bank staff from spotting warning signs. Trustworthy financial services do not need secret payments.",
   "SEBI and cybercrime fraud-prevention guidance",
   "Discuss the message with a trusted person before taking any step."),
 s("fear_exploitation","behavioral","high",62,"Fear-based pressure",
   ["your account will be seized","legal action if unpaid","police complaint against you"],
   "Threats are used to make people act without checking who is calling. Regulators and banks have formal processes and do not demand secret transfers under threats.",
   "Indian cybercrime advisories on impersonation and extortion",
   "End the conversation and contact the named organisation through its official channel."),
 s("greed_exploitation","behavioral","high",60,"Greed-based pressure",
   ["become rich quickly","double money in days","retire early with this"],
   "Fast-rich claims target hopes and hide the possibility of loss. They often lead to repeated deposits or referrals.",
   "SEBI investor education on unrealistic return claims",
   "Do not send money based on a fast-wealth promise; verify the entity first."),
 s("pressure_before_verification","behavioral","high",58,"Pressure before checking",
   ["act first verify later","no need to check registration","trust me and pay now"],
   "Refusing verification is a warning sign because legitimate providers can explain their identity and process. Pressure removes the user's chance to make a safe decision.",
   "SEBI investor-protection and intermediary-verification guidance",
   "Pause the transaction until identity, registration, and beneficiary details are checked independently."),
]

KB = {
    "version": "1.0",
    "scoring": {
        "method": "noisy-or",
        "buckets": {"safe": [0, 24], "caution": [25, 59], "high_risk": [60, 100]},
    },
    "signals": SIGNALS,
}

# --- self-validation: fail loudly rather than ship a broken brain ---
import re as _re
VALID_CAT = {"fraud", "impersonation", "misinformation", "technical", "behavioral"}
VALID_SEV = {"critical", "high", "medium", "low"}
ids = [x["id"] for x in SIGNALS]
assert len(ids) == len(set(ids)), "duplicate signal id present"
assert len(SIGNALS) >= 45, f"only {len(SIGNALS)} signals (<45)"
for sig in SIGNALS:
    sid = sig["id"]
    assert sig["category"] in VALID_CAT, f"bad category: {sid}"
    assert sig["severity"] in VALID_SEV, f"bad severity: {sid}"
    assert 0 <= sig["weight"] <= 100, f"weight out of range: {sid}"
    assert sig["label"]["en"] and sig["reason"]["en"] and sig["action"]["en"], f"empty field: {sid}"
    assert sig["citation"]["label"], f"empty citation: {sid}"
    kw, rx = sig["detect"]["keywords"], sig["detect"]["regex"]
    assert (len(kw) >= 3) or (len(rx) >= 1), f"too few detectors: {sid}"
    assert all(k == k.lower() for k in kw), f"non-lowercase keyword: {sid}"
    for r in rx:
        _re.compile(r)  # raises if the regex is invalid

out = pathlib.Path(__file__).resolve().parent.parent / "src" / "data" / "knowledge-base.json"
out.write_text(json.dumps(KB, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
by_cat = {}
for x in SIGNALS:
    by_cat[x["category"]] = by_cat.get(x["category"], 0) + 1
by_sev = {}
for x in SIGNALS:
    by_sev[x["severity"]] = by_sev.get(x["severity"], 0) + 1
print(f"OK: wrote {len(SIGNALS)} signals -> {out}")
print("by category:", by_cat)
print("by severity:", by_sev)
